# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:2022.11
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: |
            sudo add-apt-repository ppa:jonathonf/libtool
            sudo apt update
            sudo apt install g++
            sudo apt install make
            sudo apt install libtool
            sudo apt install node
      - run:
          name: "install"
          command: "npm install"
      - persist_to_workspace:
          root: workspace
          paths:
            - "root"
  test:
    docker:
      - image: cimg/node:17.2
    steps:
      - attach_workspace:
          at: workspace/root
      - run:
          name: "test"
          command: "npm test"
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - build
  test:
    jobs:
      - test
